# Generated by Django 2.1.7 on 2019-02-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Writers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Name')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Age')),
                ('email', models.CharField(blank=True, max_length=50, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Email')),
            ],
        ),
    ]
