# Generated by Django 2.1.7 on 2019-02-22 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('writers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('excerpt', models.TextField(blank=True, null=True, verbose_name='Excerpt')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('date_created', models.DateField(blank=True, null=True, verbose_name='Date created')),
                ('date_updated', models.DateField(blank=True, null=True, verbose_name='Date updated')),
                ('writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='writers.Writers')),
            ],
        ),
    ]
